#!/usr/bin/env bash

#PBS -N SampleJob
#PBS -l walltime=00:05:00
#PBS -q normal
#PBS -P vp91
#PBS -l ncpus=48
#PBS -l mem=192GB

module load python3/3.11.0 
module load cuda/12.0.0

source /scratch/abc/Training-Venv/parallel_python/bin/activate

python3 /scratch/vp91/jxj900/python-for-matlab-users/Day1/1_data_structures/4_dict.py

python3 /scratch/vp91/jxj900/python-for-matlab-users/Day1/1_data_structures/4_dict.py